#!/usr/bin/env bash

set_user_var() {
  printf "\033]1337;SetUserVar=%s=%s\007" "$1" $(echo -n "$2" | base64)
}

selected=$(
  find ~/Code -maxdepth 4 -type d -name ".git" |
    xargs dirname |
    xargs realpath --relative-to="$DIR" |
    sort -r |
    fzf \
      --layout=reverse \
      --info=inline \
      --border \
      --margin=5 \
      --padding=1
)

if [[ -z $selected ]]; then
  exit 0
fi

workspace_dir="$DIR/$selected"
set_user_var "SWITCH_WORKSPACE_DIR" "$workspace_dir"
# let wezterm keep this pane for a moment
# so it can perform the switching workspace action
sleep 0.5
