#!/usr/bin/env bash

selected=$(find ~/Code -maxdepth 4 -type d -name ".git" | xargs dirname | xargs realpath --relative-to="$HOME/Code" | sort -r | fzf)
if [[ -z $selected ]]; then
    exit 0
fi

selected="$HOME/Code/$selected"
selected_name=$(basename "$selected" | tr . _)

# create the session if needed
if ! t has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ $TMUX ]]; then
  TERM=tmux-256color tmux switch-client -t $selected_name
else
  #outside tmux
  TERM=tmux-256color tmux attach -t $selected_name
fi

